/*
 * GESMO Namespace
 * @author Shashank Ranjan
 *
 */

 var GESMO = { REVISION: '1' };

 if( typeof module === 'object' ){
 	module.exports = GESMO;
 }

 // WINDOW STATE CONSTANTS
 GESMO.MAXMODE = 0;
 GESMO.MINMODE = 1;
 GESMO.HEIGHT = window.innerHeight;
 GESMO.WIDTH = window.innerWidth;

 // NAVIGATION CONSTANTS
 GESMO.TRANSLATEX = 10;
 GESMO.TRANSLATEY = 11;
 GESMO.TRANSLATEZ = 12;
 GESMO.ROTATEX = 13;
 GESMO.ROTATEY = 14;
 GESMO.ROTATEZ = 15;
 GESMO.NOMOVE = 16;

 // GESTURE CONTROLLER CONSTANTS
 GESMO.TRANSLATEMODE = 20;
 GESMO.ROTATEMODE = 21;
 GESMO.PICKMODE = 22;
 GESMO.NOMODE = 23;
 GESMO.PI_2 = Math.PI * 2;
 GESMO.X_AXIS = new THREE.Vector3(1, 0, 0);
 GESMO.Y_AXIS = new THREE.Vector3(0, 1, 0);
 GESMO.Z_AXIS = new THREE.Vector3(0, 0, 1);

 // MUSIC PLAYER STATE CONSTANTS
 GESMO.PLAYING = 30;
 GESMO.PAUSED = 31;
 GESMO.STOPPED = 32;
 GESMO.PLAYLISTEMPTY = 34;
 GESMO.PLAYLISTNOTEMPTY = 35;

 //UI CONSTANTS
GESMO.NEWRELEASESVIEW = 3;
GESMO.TOPCHARTSVIEW = 0;
GESMO.QUEUEVIEW = 1;
GESMO.ARTISTVIEW = 2;
GESMO.Colors = {
	red: 0xf25346,
	white: 0xd8d0d1,
	brown: 0x59332e,
	pink: 0xF5986E,
	brownDark: 0x23190f,
	blue: 0x68c3c0,
	greenDark: 0x559e83,
	gray: 0xcfcfc4,
	treeColor: 0x007423
};
GESMO.LIBRARYRADIUS = 500;

 // MOUSE CONSTANTS
 GESMO.LEFTBUTTON = 0;
 GESMO.MIDDLEBUTTON = 1;
 GESMO.RIGHTBUTTON = 2;



